### ISSUE TITLE
Improve the exercise!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m1-evaluacion-intermedia-rocioferro#1]
Really cool job @rocioferro  !!!

Here you have some tips to improve the exercise:

- [x] Fix the language and the meta title of the page
- [x] Menu items should be clickable
- [x] The IMG element needs an alt attribute describing the linked image.
- [x] Move the font CSS before your main CSS
- [x] Class selectors are free, let's use them instead tag selectors 
- [x] Block elements like our main one do not need a width: 100% or width: 100vw property to tell them to do what they are going to do anyway ;)
- [x] There are some weird vertical scroll, let's remove the MAIN extra margins
- [x] Avoid uppercase/capital on HTML texts, and `BR` tags. We can transform the text with CSS; this way we keep concepts separated, HTML for content, and CSS for styles
- [x] Finish the main title styles: words should jump and the typography is super big. Remember that you have to set the H1 font-size, not the font-size container ;)
- [x] Organize your files in folders, you have a guide to help you with that here --> https://books.adalab.es/materiales-front-end-g/modulo-1.-hola-mundo/1_1_intro_a_la_web#notas-finales-sobre-como-organizar-nuestro-proyecto

Let me know if you have any doubts ;)

Go for it!!

**Comment by oneeyedman** [comment]
@rocioferro, lo doy por suficiente pero aquí están marcadas cosas que no están hechas.

**Comment by rocioferro** [comment]
Pues no te falta razón; yo creía que sí estaba todo pero lo he comprobado y
he añadido un par de cosas que claramente se me habían pasado. Las he
subido en otra rama (''arreglo''), por si quieres verlas en algún momento o
mañana en la evaluación.
Gracias!!
